# Change types
FORMAT = "FORMAT"
STRUCTURE = "STRUCTURE"
ENTITY = "ENTITY"
NUMBER = "NUMBER"
TIME = "TIME"
TERM = "TERM"
FACT = "FACT"
DELETION = "DELETION"
ADDITION = "ADDITION"
UNKNOWN = "UNKNOWN"

# Risk
LOW = "LOW"
MEDIUM = "MEDIUM"
HIGH = "HIGH"
CRITICAL = "CRITICAL"

# Route
AUTO_PASS = "AUTO_PASS"
REVIEW = "REVIEW"
REJECT = "REJECT"

# Task status
CREATED = "CREATED"
ANALYZING = "ANALYZING"
CLASSIFYING = "CLASSIFYING"
EVALUATING = "EVALUATING"
SCORING = "SCORING"
ROUTING = "ROUTING"
COMPLETED = "COMPLETED"
FAILED = "FAILED"
CANCELLED = "CANCELLED"
